#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1252
#date: Tue Oct 07 2025 00:08:37
#sha1: 5a2492
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='Shrimp', release='11', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
1547,design,log,
#design: #exp: Ternus
#design: block_cnt,block_id,trial_cnt,trial_id
1547,design,logged,
1547,Experiment,started
1548,stderr,received,'Traceback (most recent call last):'
1549,stderr,received,'  File "c:\\Users\\Claire\\progcog\\Assignments\\Week-4\\Exercises\\ternus.py", line 47, in <module>\n    run_trial()\n    ~~~~~~~~~^^'
1549,stderr,received,'  File "c:\\Users\\Claire\\progcog\\Assignments\\Week-4\\Exercises\\ternus.py", line 25, in run_trial\n    c = [make_circle(radius=50, position=-200), make_circle(radius=50, position=0), make_circle(radius=50, position=200), make_circle(radius=50, position=400)]\n         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^'
1550,stderr,received,"TypeError: make_circle() got an unexpected keyword argument 'radius'"
